import goya from '../assets/de_goya.jpg';

export const article = {
  id: 8,
  slug: "saturn",
  title: "Saturn Devouring His Son",
  date: "March 5, 2026",
  content: `
    <figure style="text-align: left; margin: 1.5rem 0;">
      <img src="${goya}" alt="Saturn Devouring His Son by Francisco de Goya" style="width: 40%; border-radius: 4px;" />
      <figcaption style="font-style: italic; font-size: 0.8em; margin-top: 0.5rem;">Francisco de Goya, 1820</figcaption>
    </figure>

    <p>Francisco De Goya painted Saturn Devouring His Son in Madrid, Spain in the 1820s as part of a set called The Black Paintings. Saturn depicts the tale of the Greco-Roman myth of Chronos (Saturn) eating his children in fear of Gaea's prophecy that he too will be overthrown by his offspring. However the painting diverges from the myth in that Goya depicts Saturn violently tearing apart his child. Saturn was painted during the Romantic period and carries themes of disillusionment with precepts of order and harmony. Goya embraces Romanticism and illustrates notions of monstrosity to create disturbance for the viewer. In particular, Goya uses certain artistic elements such as contrasting colors, Saturn's disposition and relates them to the source mythology to evoke a sensation of disgust and dissonance.</p>

    <p>There are several glaring traits in the painting that elicit a sensation of disturbance and unnaturalness. The primary focus of the painting is the mutilated corpse in the center of the canvas. The vibrant streaks of blood along the pale, innocent body immediately evokes disgust and awe for the viewer. By contrasting the dark color palette with the scarlet blood, Goya emphasizes Saturn's lifeless child as the central element of the painting. Above Saturn's left leg appears to be an erect phallus, a detail that compounds the viewer's revulsion. Yet this disgust contains a paradox, there exists a transgressive thrill in confronting such imagery, a sexual excitement derived from witnessing and hence participating in a profound disturbance. This is fundamentally about power. By presenting the phallus alongside cannibalistic violence, Goya forces us to recognize how desire and domination fuse at their darkest extreme. Saturn enacts his will upon fate itself through violence, the phallus signals not pleasure but assertion, a refusal to submit to prophecy. Similarly, Goya exercises dominance over his viewer, denying us the comfort of aesthetic distance. We cannot look away from this convergence of eroticism and horror so the painting seizes our attention and holds us accountable to our own morbid fascination. Desire and violence become inextricable as Saturn, submerged in his compulsion to control destiny, manifests power through the most primal means: consumption and procreation twisted into a single, horrifying act.</p>

    <p>In addition, Saturn almost seems to be dissociating into the canvas. For instance, Saturn's limbs seem to emerge from the dark while his upper torso is smudged with darker tones. In using these artistic elements, Goya creates an unsettling feeling in the viewer. Taking in these elements, the viewer is forced to consider the surreal nature of the painting. Saturn's Greek counterpart, Chronos, is the god of Time and as such can be perceived as the ultimate destroyer that spares nothing, even its direct kin. To consider the inevitable tide of time that shall swallow all is disturbing indeed. Even the pure innocence of children, represented by Saturn's son, must one day perish to Time. However, the most disturbing part of this painting is not the mangled body but rather Saturn's eyes which convey a frenzied sorrow. Despite being consumed by anger and madness, Saturn's eyes show that he is aware of his sins and his destiny. His eyes depict a dutiful sorrow for he must slaughter his children or perish himself. Goya enunciates this notion by his depiction of Saturn's hands. They grasp on to the bare body in what seems like an insane embrace to never let go of the child's innocence but alas, Saturn is Time and he must consume.</p>

    <p>Goya painted Saturn while aging and dying, and this proximity to death itself transforms the work into something beyond horror, it becomes autobiography. Time was not metaphor for him but predator, and he responded by creating an image so extreme it forces viewers into Saturn's trap. We become complicit in contemplating our own consumption. Every fear finds root within Time as each one is ultimately just the fear of death, which Goya manifests as Saturn. Through these calculated artistic choices, Goya does more than disturb, he implicates the viewer in Saturn's tragic awareness, forcing us to confront our own inevitable consumption by Time and the violent desperation such knowledge breeds.</p>
  `
};
